import type { Ability, Edition, Skill } from '@/schema/common';
import type { BuilderState } from './builder/builderState';
import { emptyBuilderState } from './builder/builderState';

/** A ready-to-play level-1 build. Every content id a template names must exist
 * in data/<edition>/ — all content is committed, so there's no longer an
 * "only if the pipeline has been run" caveat, but a template still breaks
 * silently if it points at an id that was renamed. */
export interface CharacterTemplate {
  id: string;
  name: string;
  blurb: string;
  edition: Edition;
  speciesRef: string;
  classRef: string;
  subclassRef?: string;
  backgroundRef: string;
  abilities: Record<Ability, number>;
  skills: Skill[];
  knownSpells: string[];
  /** 2024-only: how the background's +2/+1 ability allocation is split. */
  backgroundAbilityAllocation?: Partial<Record<Ability, number>>;
}

const TEMPLATES: CharacterTemplate[] = [
  {
    id: 'half-orc-barbarian',
    name: 'Half-Orc Barbarian',
    blurb: 'A furious front-line brawler who tanks hits and dishes out even more. Simple to play: hit things, rage when it gets bad.',
    edition: '2014',
    speciesRef: '2014/species/half-orc',
    classRef: '2014/class/barbarian',
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 15, dex: 13, con: 14, int: 10, wis: 12, cha: 8 },
    skills: ['athletics', 'perception'],
    knownSpells: [],
  },
  {
    id: 'half-elf-bard',
    name: 'Half-Elf Bard',
    blurb: 'A charismatic jack-of-all-trades who buffs allies, talks their way past trouble, and still holds their own in a fight.',
    edition: '2014',
    speciesRef: '2014/species/half-elf',
    classRef: '2014/class/bard',
    subclassRef: undefined,
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 8, dex: 14, con: 13, int: 10, wis: 12, cha: 15 },
    skills: ['performance', 'persuasion', 'deception'],
    knownSpells: [
      '2014/spell/vicious-mockery',
      '2014/spell/dancing-lights',
      '2014/spell/cure-wounds',
      '2014/spell/healing-word',
      '2014/spell/charm-person',
      '2014/spell/comprehend-languages',
    ],
  },
  {
    id: 'hill-dwarf-cleric',
    name: 'Hill Dwarf Cleric',
    blurb: "The party's healer and moral compass. Never runs out of ways to help — prepare spells fresh each day from the whole cleric list.",
    edition: '2014',
    speciesRef: '2014/species/hill-dwarf',
    classRef: '2014/class/cleric',
    subclassRef: '2014/subclass/life',
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 13, dex: 12, con: 14, int: 8, wis: 15, cha: 10 },
    skills: ['religion', 'insight'],
    knownSpells: ['2014/spell/sacred-flame', '2014/spell/guidance', '2014/spell/spare-the-dying', '2014/spell/cure-wounds', '2014/spell/bless', '2014/spell/healing-word'],
  },
  {
    id: 'elf-druid',
    name: 'Elf Druid',
    blurb: 'A shapeshifting nature guardian. Wild Shape into a beast for scouting or an early tank, or lean on nature magic instead.',
    edition: '2014',
    speciesRef: '2014/species/elf',
    classRef: '2014/class/druid',
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 8, dex: 14, con: 13, int: 12, wis: 15, cha: 10 },
    skills: ['nature', 'survival'],
    knownSpells: ['2014/spell/druidcraft', '2014/spell/produce-flame', '2014/spell/entangle', '2014/spell/healing-word', '2014/spell/faerie-fire'],
  },
  {
    id: 'human-fighter',
    name: 'Human Fighter',
    blurb: 'The most straightforward class in the game: good at hitting things with a weapon, good armor, no spells to track. A great first character.',
    edition: '2014',
    speciesRef: '2014/species/human',
    classRef: '2014/class/fighter',
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 15, dex: 13, con: 14, int: 8, wis: 12, cha: 10 },
    skills: ['athletics', 'perception'],
    knownSpells: [],
  },
  {
    id: 'halfling-monk',
    name: 'Halfling Monk',
    blurb: 'A martial artist who fights unarmed or with simple weapons, darting around the battlefield and stunning enemies with a well-placed strike.',
    edition: '2014',
    speciesRef: '2014/species/halfling',
    classRef: '2014/class/monk',
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 12, dex: 15, con: 13, int: 10, wis: 14, cha: 8 },
    skills: ['acrobatics', 'stealth'],
    knownSpells: [],
  },
  {
    id: 'dragonborn-paladin',
    name: 'Dragonborn Paladin',
    blurb: 'A holy warrior who mixes heavy armor and a big weapon with divine backup — auras, healing, and smites once they hit level 2.',
    edition: '2014',
    speciesRef: '2014/species/dragonborn',
    classRef: '2014/class/paladin',
    subclassRef: undefined,
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 15, dex: 10, con: 13, int: 8, wis: 12, cha: 14 },
    skills: ['athletics', 'persuasion'],
    knownSpells: [],
  },
  {
    id: 'elf-ranger',
    name: 'Elf Ranger',
    blurb: 'A skilled hunter and tracker with a favored enemy and terrain, good with a bow, and (from level 2) a splash of nature magic.',
    edition: '2014',
    speciesRef: '2014/species/elf',
    classRef: '2014/class/ranger',
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 12, dex: 15, con: 13, int: 10, wis: 14, cha: 8 },
    skills: ['survival', 'stealth', 'perception'],
    knownSpells: [],
  },
  {
    id: 'lightfoot-halfling-rogue',
    name: 'Lightfoot Halfling Rogue',
    blurb: "Sneaky, skilled at almost everything, and hits hard from stealth. Great for a player who wants to solve problems creatively rather than head-on.",
    edition: '2014',
    speciesRef: '2014/species/lightfoot-halfling',
    classRef: '2014/class/rogue',
    subclassRef: undefined,
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 8, dex: 15, con: 14, int: 12, wis: 13, cha: 10 },
    skills: ['stealth', 'sleightOfHand', 'perception', 'acrobatics'],
    knownSpells: [],
  },
  {
    id: 'tiefling-sorcerer',
    name: 'Tiefling Sorcerer',
    blurb: 'Innate, flexible magic — fewer spells known than a Wizard, but Metamagic to twist them in powerful ways once you level up.',
    edition: '2014',
    speciesRef: '2014/species/tiefling',
    classRef: '2014/class/sorcerer',
    subclassRef: '2014/subclass/draconic',
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 8, dex: 13, con: 14, int: 10, wis: 12, cha: 15 },
    skills: ['arcana', 'persuasion'],
    knownSpells: ['2014/spell/fire-bolt', '2014/spell/mage-hand', '2014/spell/prestidigitation', '2014/spell/ray-of-frost', '2014/spell/magic-missile', '2014/spell/mage-armor'],
  },
  {
    id: 'half-elf-warlock',
    name: 'Half-Elf Warlock',
    blurb: "Made a pact with a dark patron for power. Fewer spell slots than other casters, but they recharge on a short rest, and Eldritch Blast hits hard.",
    edition: '2014',
    speciesRef: '2014/species/half-elf',
    classRef: '2014/class/warlock',
    subclassRef: '2014/subclass/fiend',
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 8, dex: 13, con: 14, int: 10, wis: 12, cha: 15 },
    skills: ['arcana', 'deception'],
    knownSpells: ['2014/spell/eldritch-blast', '2014/spell/prestidigitation', '2014/spell/hellish-rebuke', '2014/spell/comprehend-languages'],
  },
  {
    id: 'high-elf-wizard',
    name: 'High Elf Wizard',
    blurb: 'The classic bookish spellcaster — the biggest spell list in the game, and a spellbook to add more to over time.',
    edition: '2014',
    speciesRef: '2014/species/high-elf',
    classRef: '2014/class/wizard',
    subclassRef: undefined,
    backgroundRef: '2014/background/acolyte',
    abilities: { str: 8, dex: 13, con: 14, int: 15, wis: 12, cha: 10 },
    skills: ['arcana', 'investigation'],
    knownSpells: ['2014/spell/fire-bolt', '2014/spell/mage-hand', '2014/spell/prestidigitation', '2014/spell/magic-missile', '2014/spell/shield', '2014/spell/mage-armor'],
  },

  // --- 2024 (5.5e) ---
  {
    id: '2024-orc-barbarian',
    name: 'Orc Barbarian',
    blurb: 'A furious front-line brawler who tanks hits and dishes out even more. Simple to play: hit things, rage when it gets bad.',
    edition: '2024',
    speciesRef: '2024/species/orc',
    classRef: '2024/class/barbarian',
    backgroundRef: '2024/background/soldier',
    abilities: { str: 15, dex: 13, con: 14, int: 10, wis: 12, cha: 8 },
    backgroundAbilityAllocation: { str: 2, con: 1 },
    skills: ['athletics', 'perception'],
    knownSpells: [],
  },
  {
    id: '2024-human-bard',
    name: 'Human Bard',
    blurb: 'A charismatic jack-of-all-trades who buffs allies, talks their way past trouble, and still holds their own in a fight.',
    edition: '2024',
    speciesRef: '2024/species/human',
    classRef: '2024/class/bard',
    backgroundRef: '2024/background/acolyte',
    abilities: { str: 8, dex: 14, con: 13, int: 10, wis: 12, cha: 15 },
    backgroundAbilityAllocation: { cha: 2, wis: 1 },
    skills: ['performance', 'persuasion', 'deception'],
    knownSpells: ['2024/spell/vicious-mockery', '2024/spell/dancing-lights', '2024/spell/cure-wounds', '2024/spell/healing-word'],
  },
  {
    id: '2024-dwarf-cleric',
    name: 'Dwarf Cleric',
    blurb: "The party's healer and moral compass. Never runs out of ways to help — prepare spells fresh each day from the whole cleric list.",
    edition: '2024',
    speciesRef: '2024/species/dwarf',
    classRef: '2024/class/cleric',
    backgroundRef: '2024/background/sage',
    abilities: { str: 13, dex: 12, con: 14, int: 8, wis: 15, cha: 10 },
    backgroundAbilityAllocation: { wis: 2, con: 1 },
    skills: ['religion', 'insight'],
    knownSpells: ['2024/spell/sacred-flame', '2024/spell/guidance', '2024/spell/spare-the-dying', '2024/spell/cure-wounds', '2024/spell/bless', '2024/spell/healing-word'],
  },
  {
    id: '2024-elf-druid',
    name: 'Elf Druid',
    blurb: 'A shapeshifting nature guardian. Wild Shape into a beast for scouting or an early tank, or lean on nature magic instead.',
    edition: '2024',
    speciesRef: '2024/species/elf',
    classRef: '2024/class/druid',
    backgroundRef: '2024/background/sage',
    abilities: { str: 8, dex: 14, con: 13, int: 12, wis: 15, cha: 10 },
    backgroundAbilityAllocation: { wis: 2, int: 1 },
    skills: ['nature', 'survival'],
    knownSpells: ['2024/spell/druidcraft', '2024/spell/produce-flame', '2024/spell/entangle', '2024/spell/healing-word', '2024/spell/faerie-fire'],
  },
  {
    id: '2024-human-fighter',
    name: 'Human Fighter',
    blurb: 'The most straightforward class in the game: good at hitting things with a weapon, good armor, no spells to track. A great first character.',
    edition: '2024',
    speciesRef: '2024/species/human',
    classRef: '2024/class/fighter',
    backgroundRef: '2024/background/soldier',
    abilities: { str: 15, dex: 13, con: 14, int: 8, wis: 12, cha: 10 },
    backgroundAbilityAllocation: { str: 2, con: 1 },
    skills: ['athletics', 'perception'],
    knownSpells: [],
  },
  {
    id: '2024-halfling-monk',
    name: 'Halfling Monk',
    blurb: 'A martial artist who fights unarmed or with simple weapons, darting around the battlefield and stunning enemies with a well-placed strike.',
    edition: '2024',
    speciesRef: '2024/species/halfling',
    classRef: '2024/class/monk',
    backgroundRef: '2024/background/soldier',
    abilities: { str: 12, dex: 15, con: 13, int: 10, wis: 14, cha: 8 },
    backgroundAbilityAllocation: { dex: 2, con: 1 },
    skills: ['acrobatics', 'stealth'],
    knownSpells: [],
  },
  {
    id: '2024-dragonborn-paladin',
    name: 'Dragonborn Paladin',
    blurb: 'A holy warrior who mixes heavy armor and a big weapon with divine backup — auras, healing, and smites once they hit level 2.',
    edition: '2024',
    speciesRef: '2024/species/dragonborn',
    classRef: '2024/class/paladin',
    backgroundRef: '2024/background/soldier',
    abilities: { str: 15, dex: 10, con: 13, int: 8, wis: 12, cha: 14 },
    backgroundAbilityAllocation: { str: 2, con: 1 },
    skills: ['athletics', 'persuasion'],
    knownSpells: [],
  },
  {
    id: '2024-elf-ranger',
    name: 'Elf Ranger',
    blurb: 'A skilled hunter and tracker with a favored enemy and terrain, good with a bow, and (from level 2) a splash of nature magic.',
    edition: '2024',
    speciesRef: '2024/species/elf',
    classRef: '2024/class/ranger',
    backgroundRef: '2024/background/soldier',
    abilities: { str: 12, dex: 15, con: 13, int: 10, wis: 14, cha: 8 },
    backgroundAbilityAllocation: { dex: 2, con: 1 },
    skills: ['survival', 'stealth', 'perception'],
    knownSpells: [],
  },
  {
    id: '2024-halfling-rogue',
    name: 'Halfling Rogue',
    blurb: 'Sneaky, skilled at almost everything, and hits hard from stealth. Great for a player who wants to solve problems creatively rather than head-on.',
    edition: '2024',
    speciesRef: '2024/species/halfling',
    classRef: '2024/class/rogue',
    backgroundRef: '2024/background/criminal',
    abilities: { str: 8, dex: 15, con: 14, int: 12, wis: 13, cha: 10 },
    backgroundAbilityAllocation: { dex: 2, int: 1 },
    skills: ['stealth', 'sleightOfHand', 'perception', 'acrobatics'],
    knownSpells: [],
  },
  {
    id: '2024-tiefling-sorcerer',
    name: 'Tiefling Sorcerer',
    blurb: 'Innate, flexible magic — fewer spells known than a Wizard, but Metamagic to twist them in powerful ways once you level up.',
    edition: '2024',
    speciesRef: '2024/species/tiefling',
    classRef: '2024/class/sorcerer',
    backgroundRef: '2024/background/acolyte',
    abilities: { str: 8, dex: 13, con: 14, int: 10, wis: 12, cha: 15 },
    backgroundAbilityAllocation: { cha: 2, int: 1 },
    skills: ['arcana', 'persuasion'],
    knownSpells: ['2024/spell/fire-bolt', '2024/spell/mage-hand', '2024/spell/prestidigitation', '2024/spell/ray-of-frost', '2024/spell/magic-missile', '2024/spell/mage-armor'],
  },
  {
    id: '2024-tiefling-warlock',
    name: 'Tiefling Warlock',
    blurb: 'Made a pact with a dark patron for power. Fewer spell slots than other casters, but they recharge on a short rest, and Eldritch Blast hits hard.',
    edition: '2024',
    speciesRef: '2024/species/tiefling',
    classRef: '2024/class/warlock',
    backgroundRef: '2024/background/acolyte',
    abilities: { str: 8, dex: 13, con: 14, int: 10, wis: 12, cha: 15 },
    backgroundAbilityAllocation: { cha: 2, int: 1 },
    skills: ['arcana', 'deception'],
    knownSpells: ['2024/spell/eldritch-blast', '2024/spell/prestidigitation', '2024/spell/hellish-rebuke', '2024/spell/comprehend-languages'],
  },
  {
    id: '2024-gnome-wizard',
    name: 'Gnome Wizard',
    blurb: 'The classic bookish spellcaster — the biggest spell list in the game, and a spellbook to add more to over time.',
    edition: '2024',
    speciesRef: '2024/species/gnome',
    classRef: '2024/class/wizard',
    backgroundRef: '2024/background/sage',
    abilities: { str: 8, dex: 13, con: 14, int: 15, wis: 12, cha: 10 },
    backgroundAbilityAllocation: { int: 2, con: 1 },
    skills: ['arcana', 'investigation'],
    knownSpells: ['2024/spell/fire-bolt', '2024/spell/mage-hand', '2024/spell/prestidigitation', '2024/spell/magic-missile', '2024/spell/shield', '2024/spell/mage-armor'],
  },
];

export function listTemplates(edition: Edition): CharacterTemplate[] {
  return TEMPLATES.filter((t) => t.edition === edition);
}

/** Turns a template into a BuilderState the same factory the wizard uses can build a Character from. */
export function templateToBuilderState(template: CharacterTemplate): BuilderState {
  return {
    ...emptyBuilderState(),
    edition: template.edition,
    name: '',
    baseAbilities: template.abilities,
    speciesRef: template.speciesRef,
    classRef: template.classRef,
    subclassRef: template.subclassRef,
    backgroundRef: template.backgroundRef,
    backgroundAbilityAllocation: template.backgroundAbilityAllocation ?? {},
    classDecisions: [{ decisionId: `${template.classRef.split('/').pop()}/skills`, choice: template.skills }],
    knownSpells: template.knownSpells,
  };
}
